-- =============================================================================
-- STAGE TABLES CREATION
-- =============================================================================
-- These tables will store complete historical data loaded via Snowpipe
-- Each table includes a record timestamp and version tracking
-- =============================================================================

USE SCHEMA SNOWPIPE_DT_DEMO.STAGE_DATA;

-- 1. CUSTOMER INFORMATION STAGE TABLE
CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    ADDRESS STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    COUNTRY STRING,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. PRODUCT INFORMATION STAGE TABLE
CREATE OR REPLACE TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUBCATEGORY STRING,
    BRAND STRING,
    PRICE NUMBER(10,2),
    COST NUMBER(10,2),
    SUPPLIER_ID NUMBER,
    DESCRIPTION STRING,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. ORDERS STAGE TABLE
CREATE OR REPLACE TABLE STG_ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    ORDER_STATUS STRING,
    ORDER_TOTAL NUMBER(10,2),
    PAYMENT_METHOD STRING,
    SHIPPING_ADDRESS STRING,
    BILLING_ADDRESS STRING,
    ORDER_PRIORITY STRING,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. ORDER ITEMS STAGE TABLE
CREATE OR REPLACE TABLE STG_ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT_PERCENT NUMBER(5,2),
    LINE_TOTAL NUMBER(10,2),
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. SUPPLIERS STAGE TABLE
CREATE OR REPLACE TABLE STG_SUPPLIERS (
    SUPPLIER_ID NUMBER,
    SUPPLIER_NAME STRING,
    CONTACT_PERSON STRING,
    EMAIL STRING,
    PHONE STRING,
    ADDRESS STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    RATING NUMBER(2,1),
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. INVENTORY STAGE TABLE
CREATE OR REPLACE TABLE STG_INVENTORY (
    INVENTORY_ID NUMBER,
    PRODUCT_ID NUMBER,
    WAREHOUSE_ID NUMBER,
    QUANTITY_ON_HAND NUMBER,
    QUANTITY_RESERVED NUMBER,
    QUANTITY_AVAILABLE NUMBER,
    REORDER_LEVEL NUMBER,
    REORDER_QUANTITY NUMBER,
    LAST_UPDATED TIMESTAMP_NTZ,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. WAREHOUSES STAGE TABLE
CREATE OR REPLACE TABLE STG_WAREHOUSES (
    WAREHOUSE_ID NUMBER,
    WAREHOUSE_NAME STRING,
    LOCATION STRING,
    CAPACITY NUMBER,
    CURRENT_UTILIZATION NUMBER,
    MANAGER_ID NUMBER,
    PHONE STRING,
    ADDRESS STRING,
    CITY STRING,
    STATE STRING,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. EMPLOYEES STAGE TABLE
CREATE OR REPLACE TABLE STG_EMPLOYEES (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    DEPARTMENT STRING,
    POSITION STRING,
    SALARY NUMBER(10,2),
    HIRE_DATE DATE,
    MANAGER_ID NUMBER,
    ADDRESS STRING,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 9. SALES TERRITORIES STAGE TABLE
CREATE OR REPLACE TABLE up (
    TERRITORY_ID NUMBER,
    TERRITORY_NAME STRING,
    REGION STRING,
    COUNTRY STRING,
    SALES_REP_ID NUMBER,
    QUOTA NUMBER(12,2),
    ACTUAL_SALES NUMBER(12,2),
    TERRITORY_STATUS STRING,
    START_DATE DATE,
    END_DATE DATE,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 10. PROMOTIONS STAGE TABLE
CREATE OR REPLACE TABLE STG_PROMOTIONS (
    PROMOTION_ID NUMBER,
    PROMOTION_NAME STRING,
    PROMOTION_TYPE STRING,
    DISCOUNT_PERCENT NUMBER(5,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    START_DATE DATE,
    END_DATE DATE,
    APPLICABLE_PRODUCTS STRING,
    MIN_ORDER_AMOUNT NUMBER(10,2),
    MAX_USES NUMBER,
    CURRENT_USES NUMBER,
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION NUMBER,
    RECORD_STATUS STRING DEFAULT 'ACTIVE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Show all created stage tables
SHOW TABLES IN SCHEMA SNOWPIPE_DT_DEMO.STAGE_DATA;
