-- =============================================================================
-- INTERNAL STAGES CREATION
-- =============================================================================
-- Create internal stages for each table where JSON files will be uploaded
-- These stages will be monitored by Snowpipe for automatic data loading
-- JSON files will leverage Snowflake's advanced schema detection capabilities
-- =============================================================================

USE SCHEMA SNOWPIPE_DT_DEMO.DEMO_STAGES;

-- Create internal stages for each table
CREATE OR REPLACE STAGE STG_CUSTOMERS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_PRODUCTS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_ORDERS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_ORDER_ITEMS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_SUPPLIERS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_INVENTORY_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_WAREHOUSES_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_EMPLOYEES_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_SALES_TERRITORIES_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

CREATE OR REPLACE STAGE STG_PROMOTIONS_FILES
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
  );

-- Show all created stages
SHOW STAGES IN SCHEMA SNOWPIPE_DT_DEMO.DEMO_STAGES;
