-- =============================================================================
-- SNOWPIPE CREATION WITH JSON SUPPORT - CORRECTED
-- =============================================================================
-- Create Snowpipe objects that load JSON data into pre-defined tables
-- 
-- IMPORTANT CORRECTIONS:
-- ❌ INFER_SCHEMA = TRUE is NOT a valid Snowpipe parameter (causes compilation error)
-- ❌ FORCE = TRUE is NOT a valid Snowpipe parameter (causes compilation error)
-- ✅ INFER_SCHEMA is a table function used for schema detection during table creation
-- ✅ Snowpipe uses MATCH_BY_COLUMN_NAME to map JSON fields to existing table columns
-- ✅ JSON file format handles the actual JSON parsing during data load
-- ✅ For force loading, use ALTER PIPE ... REFRESH commands (see bottom of script)
-- 
-- For schema detection, see script: 03B_json_schema_detection.sql
-- =============================================================================

USE SCHEMA SNOWPIPE_DT_DEMO.STAGE_DATA;

-- 1. CUSTOMERS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = NULL  -- For internal stages, this is not needed
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_CUSTOMERS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_CUSTOMERS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 2. PRODUCTS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_PRODUCTS
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_PRODUCTS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_PRODUCTS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 3. ORDERS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_ORDERS
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_ORDERS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_ORDERS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 4. ORDER ITEMS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_ORDER_ITEMS
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_ORDER_ITEMS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_ORDER_ITEMS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 5. SUPPLIERS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_SUPPLIERS
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_SUPPLIERS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_SUPPLIERS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 6. INVENTORY SNOWPIPE
CREATE OR REPLACE PIPE PIPE_INVENTORY
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_INVENTORY
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_INVENTORY_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 7. WAREHOUSES SNOWPIPE
CREATE OR REPLACE PIPE PIPE_WAREHOUSES
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_WAREHOUSES
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_WAREHOUSES_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 8. EMPLOYEES SNOWPIPE
CREATE OR REPLACE PIPE PIPE_EMPLOYEES
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_EMPLOYEES
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_EMPLOYEES_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 9. SALES TERRITORIES SNOWPIPE
CREATE OR REPLACE PIPE PIPE_SALES_TERRITORIES
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_SALES_TERRITORIES
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_SALES_TERRITORIES_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- 10. PROMOTIONS SNOWPIPE
CREATE OR REPLACE PIPE PIPE_PROMOTIONS
AUTO_INGEST = TRUE
AS
COPY INTO SNOWPIPE_DT_DEMO.STAGE_DATA.STG_PROMOTIONS
FROM @SNOWPIPE_DT_DEMO.DEMO_STAGES.STG_PROMOTIONS_FILES/
FILE_FORMAT = (
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    REPLACE_INVALID_CHARACTERS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- Show all created pipes
SHOW PIPES IN SCHEMA SNOWPIPE_DT_DEMO.STAGE_DATA;

-- Check pipe status after creation
SELECT 
    PIPE_NAME,
    IS_AUTOINGEST_ENABLED,
    PIPE_STATUS,
    DEFINITION
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- =============================================================================
-- FORCE LOADING: ALTER PIPE REFRESH (when needed)
-- =============================================================================
-- ⚠️  NOTE: FORCE parameter is NOT valid in Snowpipe definitions!
-- Instead, use ALTER PIPE ... REFRESH to reload files that were already processed
-- This is the correct way to force reload in Snowpipe for demos/troubleshooting

-- UNCOMMENT THESE COMMANDS WHEN YOU NEED TO FORCE RELOAD FILES:
/*
ALTER PIPE PIPE_CUSTOMERS REFRESH;
ALTER PIPE PIPE_PRODUCTS REFRESH;
ALTER PIPE PIPE_ORDERS REFRESH;
ALTER PIPE PIPE_ORDER_ITEMS REFRESH;
ALTER PIPE PIPE_SUPPLIERS REFRESH;
ALTER PIPE PIPE_INVENTORY REFRESH;
ALTER PIPE PIPE_WAREHOUSES REFRESH;
ALTER PIPE PIPE_EMPLOYEES REFRESH;
ALTER PIPE PIPE_TERRITORIES REFRESH;
ALTER PIPE PIPE_PROMOTIONS REFRESH;
*/

-- Monitor individual pipe status
SELECT SYSTEM$PIPE_STATUS('PIPE_CUSTOMERS') as CUSTOMERS_STATUS;
SELECT SYSTEM$PIPE_STATUS('PIPE_PRODUCTS') as PRODUCTS_STATUS;
SELECT SYSTEM$PIPE_STATUS('PIPE_ORDERS') as ORDERS_STATUS;

SELECT 'All Snowpipes created successfully!' as STATUS;
SELECT 'Use ALTER PIPE ... REFRESH commands above to force reload files if needed' as FORCE_RELOAD_INFO;
